language: node_js
node_js:
  - "11.11.0"
install:
  - npm ci
stages:
  - lint
  - build
  - deploy
jobs:
  include:
    - stage: lint
      script:
        # Run linter
        - npm run lint
    - stage: build
      script:
        # Build all
        - npm run build
    - stage: deploy
      deploy:
        provider: pages
        skip-cleanup: true
        local_dir: dist
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        on:
          branch: master